### * RNN 주요 레이어 종류
#### (1) SimpleRNN :가장 간단한 형태의 RNN레이어, 활성화 함수로 tanh가 사용됨(tanh: -1 ~ 1 사이의 값을 반환)
#### (2) LSTM(Long short Term Memory) : 입력 데이터와 출력 사이의 거리가 멀어질수로 연관 관계가 적어진다(Long Term Dependency,장기의존성 문제), LSTM은 장기 의존성 문제를 해결하기 위해 출력값외에 셀상태(cell state)값을 출력함, 활성화 함수로 tanh외에 sigmoid가 사용됨
#### (3) GRU(Gated Recurent Unit) : 뉴욕대 조경현 교수 등이 제안, LSTM보다 구조가 간단하고 성능이 우수함

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Sequence data
X = np.array([[0,1,2,3],
              [1,2,3,4],
              [2,3,4,5],
              [3,4,5,6],
              [4,5,6,7],
              [5,6,7,8]],dtype=np.float32)

x_data = tf.reshape(X,(-1,4,1))  # (6,4,1)

y_data = np.array([4,5,6,7,8,9],dtype=np.float32)

print(x_data.shape,y_data.shape)
# print(type(x_data),type(y_data))
x_data

(6, 4, 1) (6,)


<tf.Tensor: shape=(6, 4, 1), dtype=float32, numpy=
array([[[0.],
        [1.],
        [2.],
        [3.]],

       [[1.],
        [2.],
        [3.],
        [4.]],

       [[2.],
        [3.],
        [4.],
        [5.]],

       [[3.],
        [4.],
        [5.],
        [6.]],

       [[4.],
        [5.],
        [6.],
        [7.]],

       [[5.],
        [6.],
        [7.],
        [8.]]], dtype=float32)>

### [1] SimpleRNN
#### 가장 간단한 형태의 RNN 

In [13]:
# RNN 순환 신경망 구현  : SimpleRNN
model = tf.keras.Sequential([
    # X: (N,D) , Wx:(D,H), Wh : (H,H), b: H
    #    (6,1)    (1,300)    (300,300)  300  --> 1*300+300*300+300 = 90600개의 Param
    # (N,T,D) : (6,4,1)  ---> (N,T,H) : (6,4,300) , T는 sequence_length, H는 Hidden Size
    # return_sequences=True는 3차원(N,T,H)로 출력 
    # return_sequences=False는 2차원(N,H)로 출력 ,기본 값

    tf.keras.layers.SimpleRNN(units=300,return_sequences=True,input_shape=(4,1)),
    tf.keras.layers.SimpleRNN(units=300),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam',loss='mse')
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_11 (SimpleRNN)   (None, 4, 300)            90600     
                                                                 
 simple_rnn_12 (SimpleRNN)   (None, 300)               180300    
                                                                 
 dense_2 (Dense)             (None, 1)                 301       
                                                                 
Total params: 271,201
Trainable params: 271,201
Non-trainable params: 0
_________________________________________________________________


In [14]:
# 학습 및 예측
model.fit(x_data,y_data,epochs=100)
print(model.predict(x_data))

Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 49.1176
Epoch 2/100
1/1 [==============================] - 0s 16ms/step - loss: 1.4358
Epoch 3/100
1/1 [==============================] - 0s 37ms/step - loss: 5.8578
Epoch 4/100
1/1 [==============================] - 0s 71ms/step - loss: 8.4519
Epoch 5/100
1/1 [==============================] - 0s 33ms/step - loss: 4.8521
Epoch 6/100
1/1 [==============================] - 0s 29ms/step - loss: 1.6162
Epoch 7/100
1/1 [==============================] - 0s 17ms/step - loss: 2.0512
Epoch 8/100
1/1 [==============================] - 0s 11ms/step - loss: 3.7644
Epoch 9/100
1/1 [==============================] - 0s 14ms/step - loss: 3.6613
Epoch 10/100
1/1 [==============================] - 0s 10ms/step - loss: 2.2605
Epoch 11/100
1/1 [==============================] - 0s 11ms/step - loss: 1.1009
Epoch 12/100
1/1 [==============================] - 0s 11ms/step - loss: 0.7756
Epoch 13/100
1/1 [==============================] 

In [12]:
y_data

array([4., 5., 6., 7., 8., 9.], dtype=float32)

In [16]:
# 학습되지 않은 입력 데이터에 대한 예측 결과
print(model.predict(np.array([[[6.],[7.],[8.],[9.]]])))
print(model.predict(np.array([[[-1.],[0.],[1.],[2.]]])))

1/1 [==============================] - 0s 20ms/step
[[9.487042]]
1/1 [==============================] - 0s 19ms/step
[[1.2237161]]


In [17]:
# 평가
model.evaluate(x_data, y_data)

1/1 [==============================] - 0s 285ms/step - loss: 0.0057


0.005651883315294981